# fly.toml app configuration file generated for runit on 2023-09-08T10:10:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "runit"
primary_region = "hkg"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "5000"
  RUNIT_SERVERNAME='runit.fly.dev'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
