name: Docker Push

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          TAG="theonlyamos/runit_server:${{ github.event.release.tag_name }}"
          docker build . --file Dockerfile --tag $TAG
          echo "::set-output name=tag::$TAG" # Set the output variable
        id: build_docker_image

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: theonlyamos
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push Docker image
        run: |
          echo Image name is ${{ steps.build_docker_image.outputs.tag }}
          docker push ${{ steps.build_docker_image.outputs.tag }} # Use the saved tag variable
